djangolevel5/basic_app/urls.py
from django.urls import path
from .  import views


app_name="basic_app"

urlpatterns=[
    path('',views.index,name="index"),
    path('registration/',views.registration,name="registration"),
    path('login_user/',views.login_user,name="login_user"),
]

djangolevel5/djangolevel5/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from basic_app import views

urlpatterns = [
    path('', views.index,name="index"),
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name="logout"),
]

djangolevel5/basic_app/models.py
from django.db import models
from django.contrib.auth.models  import User

class User_Profile_info(models.Model):

    user=models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio=models.URLField(blank=True)

    profile_pics=models.ImageField(upload_to="profile_pics",blank=True)


    def __str__(self):
        return self.user.username

# Create your models here.

djangolevel5/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import User_Profile_info

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileForm(forms.ModelForm):

    class Meta():
        model=User_Profile_info
        fields=('portfolio','profile_pics')

djangolevel5/basic_app/views.py
from django.shortcuts import render
from django import forms
from basic_app.forms import UserForm,UserProfileForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
# Create your views here.


def index(request):
    return render(request,'basic_app/index.html')

def registration(request):
    registered=False
    if request.method=="POST":
       user_form=UserForm(data=request.POST)
       user_profile_form=UserProfileForm(data=request.POST)
       if user_form.is_valid() and user_profile_form.is_valid():
           user=user_form.save()
           user.set_password(user.password)
           user.save()

           profile=user_profile_form.save(commit=False)
           profile.user=user
           if 'profile_pic' in request.FILES:
               profile.profile_pic=request.FILES['profile_pic']

           profile.save()
           registered=True
       else:
           print(user_form.errors,user_profile_form.errors)
    else:
        user_form=UserForm()
        user_profile_form=UserProfileForm()

    return render (request,'basic_app/registration.html',{'registered':registered,'UserForm':user_form,'UserProfileForm':user_profile_form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def login_user(request):

    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")

        user=authenticate(username=username,password=password)


        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else :
                return HttpResponse("Acccount not active")

        else :
            print("someone tried to login and failed")
            print("username :{} and password={}").format(username,password)
            return HttpResponse("invalid login details suppplied")
    else:
        return render(request,'basic_app/login.html')

djangolevel5/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li> <a class="navbar-brand" href="{% url 'basic_app:index' %}">DJANGO</a></li>
            <li><a class="navbar-brand" href="{% url 'admin:index' %}">ADMIN</a></li>
            <li><a class="navbar-brand" href="{% url 'basic_app:registration' %}">Registration</a></li>

            {% if user.is_authenticated %}:
                 <li><a class="navbar-brand" href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a class="navbar-brand" href="{% url 'basic_app:login_user' %}">Login</a></li>
            {% endif %}


        </ul>
    </div>
</nav>

<div class="container">
    {% block body_block %}

    {% endblock %}
</div>

</body>
</html>

djangolevel5/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div classs="jumbotron">
    <h1>Django Level Five</h1>

</div>

{% endblock %}

djangolevel5/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="container">
    <h1>Please Login </h1>
    <form action="{% url 'basic_app:login_user' %}" method="post">
         {% csrf_token %}
        <label for ="username">Username:</label>
        <input type="text" placeholder="Enterusername"  name="username">
        <label for ="password">Password:</label>
        <input type="password"   name="password">
        <input type="Submit" value="Login">

    </form>
</div>
{% endblock %}

djangolevel5/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">

    {% if registered %}
    <h1> Thank you for registering></h1>

    {% else %}
    <h1>Register Here!</h1>
    <h1> Fill out the form </h1>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{UserForm.as_p}}
        {{UserProfileForm.as_p}}
        <input type="submit" name="Register" value="Register">
    </form>

    {% endif %}


</div>

{% endblock %}